### ISSUE TITLE
Feature Request: A way to hide and show quest objectives.

### ISSUE THREAD

**Issue by SalieriC** [Forien/foundryvtt-forien-quest-log#10]
A way to hide quest objectives by default and revealing them one by one as the players continue to progress in order to not spoiler them up front would be very great.

**Comment by Forien** [comment]
Both `hiding individual tasks` and `a toggle "hide future tasks from players"` are often requested features that both are on [a TODO list](https://github.com/Forien/foundryvtt-forien-quest-log#future-plans-current-ideas) that you can check in `README.md` file. 

`Hiding specific tasks` will for sure be in nearest update ;)

**Comment by Forien** [comment]
closed by #24
