### ISSUE TITLE
[BUG] Can't close out of the "Add new Quest" window

### ISSUE THREAD

**Issue by yoshikidneo** [Forien/foundryvtt-forien-quest-log#107]
**Module Version:** v0.0.0

**Describe the bug**
When I open the quest log, I can add quest and things like that, but I cannot close out of the "Add new Quest" popup window.

**To Reproduce**
1. Go to "Quest Log" in the journal entries tab
2. Click on "Add new Quest"
3. Try to close the new pop-out window.

**Browser:**
 Self-Hosted Application

**Foundry Version:** 
0.7.7

**Game System:** 

DND 5e 1.1.1

**Comment by DuskyVoltage** [comment]
Check [#105](https://github.com/Forien/foundryvtt-forien-quest-log/issues/105)

**Comment by yoshikidneo** [comment]
Good looking out!
