### ISSUE TITLE
Feature Request Quest Chains

### ISSUE THREAD

**Issue by card2112** [Forien/foundryvtt-forien-quest-log#11]
Would be cool if we could have an overreaching quest with the ability to make subquests inside of it where each subquests might have it's own quest giver and tasks.

**Comment by Forien** [comment]
As in my [TODO List](https://github.com/Forien/foundryvtt-forien-quest-log#future-plans-current-ideas) there is item called "quest branching". What I intend to do is actually just allow for linking quests. A Game Master will be able to define in advance several possible subquests and as players complete objectives, GM will be able to activate a branch, which will be it's own standalone quest, but linking and being linked in parent Quest :) 

I'm currently working on _v0.3.0_, and Quest Linking/branching will probably come later

**Comment by card2112** [comment]
Sorry, didn't see that. Sounds excellent! Really great module and thanks for making it available!

**Comment by Forien** [comment]
@card2112 Don't be sorry, it's great when people make requests :) at least I know people are using my Module and enjoying it :)

And it also helps me prioritise features for future updates
