### ISSUE TITLE
[BUG] Unable to close Quest Tracker

### ISSUE THREAD

**Issue by Kev1112005** [Forien/foundryvtt-forien-quest-log#128]
**Module Version:** v0.7.9

**Describe the bug**
When I open the quest tracker, I am unable to minimize or close the quest tracker. 

**To Reproduce**
1. Go to Journal Notes button on the left side of the menu.
2. Click on Quest Tracker button.
3. Attempt to close/minimize the window.

**Expected behavior**
I expect that the window would minimize or close, like other windows. Instead, they stay stuck.

**Screenshots**
![image](https://user-images.githubusercontent.com/30413531/147168636-d08c42b8-9284-45c7-b5c2-52b3828dada5.png)

**Browser:**
 - Brave Browser, v1.33.106
 - Safari, v15.0 (16612.1.29.41.4, 16612)

**Foundry Version:** 
 - v0.8.9

**Game System:** 
 - DnD5e v1.5.6

**Additional context**
Add any other context (like other modules installed) about the problem here.
Active Modules:
----------
Advanced Spell Effects v0.8.5.5;
Ambient Doors v2.2.5;
Ammo Tracker v0.2.1;
Automated Animations v0.6.69;
Bellows v0.4.1;
Better Text Drawings v1.1.1.0;
Boss Bar v0.7.6;
Caeora's Maps, Tokens, and Assets v1.0.4;
Changelogs &amp; Conflicts v0.7.5;
Combat Enhancements v1.0.2;
Combat Numbers v1.2.0;
Combat Utility Belt v1.7.3;
CommunityLighting by Blitz v0.4.7;
Compendium Folders v2.3.64;
D&amp;D Beyond Importer v2.7.2;
Dice So Nice! v4.2.2;
Drag Upload (Get Over Here!) v2.0.0;
Dynamic effects using Active Effects v0.8.75;
Find the culprit v1.4.0;
Forien's Quest Log v0.7.9;
Forien's Token Rotation v0.1.1;
Forien's Unidentified Items v0.3.17;
FoundryVTT Arms Reach v2.1.6;
FXMaster v2.0.0;
Image Hover v1.1.8;
JB2A - Jules and Ben's Animated Assets - Free Content v0.3.3;
Keybind Lib v0.3.4;
Koboldworks – Ready Up! v0.3.3.3;
Let Me Roll That For You! v1.21;
lib - Color Settings v2.8.1;
Lib: Document Sheet Registrar v0.6.3;
libWrapper v1.11.0.1;
Loot Sheet NPC 5e v3.3.8;
Lordu's Custom Dice for Dice So Nice v0.33;
Michael Ghelfi Studios Audio Pack v1.3;
Midi QOL v0.8.96;
Monk's Active Tile Triggers v1.0.38;
Monk's Enhanced Journal v1.0.33;
Multiattack 5e v5.2.1;
Multiface Tiles v1.0.2;
Negative HP v1.1.0;
Nice More Dice v1.0.3;
Not Your Turn! v1.1.5;
Perfect Vision v2.10.8;
Permission Viewer v0.8.14;
Pings v1.2.12+0.8.6;
Playlist Drag and Drop v1.2.0;
Playlist Enhancer v1.1.3;
Polyglot v1.7.28;
PopOut! v2.4;
Popout Resizer v1.4.1;
Quick Encounters v0.9.4;
QuickScale v1.3.0;
Rarity Colors v0.1.03;
Search Anywhere v2.2.1;
Sequencer v1.3.5;
Settings Extender v1.2.0;
Simple Calendar vv1.3.75;
socketlib v1.0.9;
SoundBoard by Blitz v1.5.3;
SoundBoard Pack - Community v1.0.1;
Storyteller v0.2.3;
Sync Token Names v1.0.2;
Tagger v1.2.1;
Talis Dice v1.0.6;
Tidy UI - Game Settings v0.1.28;
Toggle Combat Warning v0.1.9;
Token Action HUD v1.3.29;
Token Attacher v4.2.1;
Tokenizer v3.4.13;
Token Replacer v0.6.1;
TorchLight v0.10.0;
Universal Battlemap Importer v2.2.1;
Weather Control v4.1.3;
Wild Magic Surge 5e v1.6.0;
Window Controls v1.5.3;

Inactive Modules:
----------
Lock View v1.4.14;

**Comment by typhonrt** [comment]
Thanks @Kev1112005 for posting an issue. I can't reproduce this issue. I see that you have some sort of module affecting the top header bar. The `_` and `eye glass` icons are not part of FQL, so I'd look at whatever module is adding those icons and disable it to confirm it is not a conflict with another module. There is nothing fancy with the FQL header buttons including the close button. 

Perhaps disable all module except FQL and try again. 

I'm leaning toward this is a `won't fix` issue. IE if the quest tracker couldn't be closed normally plenty of people would complain about it.

**Comment by Kev1112005** [comment]
Hey @typhonrt,

Thanks for the quick response! I did confirm that this appears to be an issue with Window Controls. I disabled the module and it appears to close out properly. Thanks! I also took note of the FQL repo change. Thanks!
