### ISSUE TITLE
V12 Will not even show up in available list

### ISSUE THREAD

**Issue by Cedric-the-Destroyer** [Forien/foundryvtt-forien-quest-log#132]
Newest update for Quest Log

Foundry 12.327

**Comment by typhonrt** [comment]
Not a bug... Max version currently is v11. A v12 update is being worked on. Refer to the actual repo: 
https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/issues/44

**Comment by Cedric-the-Destroyer** [comment]
Thanks for the response. Why are there two githubs? 

Anywho, thanks again, have a good night
