### ISSUE TITLE
FoundryV12 compatibility

### ISSUE THREAD

**Issue by zarazandra** [Forien/foundryvtt-forien-quest-log#133]
As the title says, I'd love to continue using the questlog for my v12-instances.

**Comment by typhonrt** [comment]
FQL is still being developed on a fork. The v12 issue is here to monitor:
https://github.com/League-of-Foundry-Developers/foundryvtt-forien-quest-log/issues/44

I'm almost done with the v12 update.

**Comment by Tridus** [comment]
This is done now.
