### ISSUE TITLE
[BUG] Unable to award using the new 5e "award" option

### ISSUE THREAD

**Issue by MaineKnight** [Forien/foundryvtt-forien-quest-log#135]
**Module Version:** v0.8.0

**Describe the bug**
When I create a "group" and set it to encounter or group I am able to open it an click the assign button and it opens the award popup. I dragged the group I created to the rewards section and it opens the group window, but the award button doesn't work. If I go back to the group again the award button works.

**Expected behavior**
I would expect to be able to create groups to use as encounters and/or loot and be able to award them to the players.

**Foundry Version:**  V12 (329)

**Comment by typhonrt** [comment]
Hi @MaineKnight... `v0.8.0` hasn't quite shipped yet / posted in the official package manager. It will soon, so verifying that you have indeed installed the latest version of the module is useful in this case. I'll be putting together a brief overview video of using FQL with Item Piles and the text enrichment option of the `dnd5e` game system. 

There is not enough information in your post above to verify if you are using the general feature as designed. Perhaps you can write down the steps and include some images of exactly what you tried.

As mentioned though verifying that you are on the latest install is the first order of business.

**Comment by MaineKnight** [comment]
Hi,

I had used the json path from installation section on this page: https://github.com/Forien/foundryvtt-forien-quest-log
![Version](https://github.com/user-attachments/assets/44049e89-e4cc-420c-9b34-4c5663d1048d)

Steps:


1) Created a group with some loot assigned. This way I can just hit the award button and assign the loot as needed.

![Group-Alone](https://github.com/user-attachments/assets/cf7391f4-f1b6-4848-923d-3e16d5544565)

2) Then I assigned it to the quest and checked the award still worked, but the button was inactive.

![Group-Quest](https://github.com/user-attachments/assets/f6750782-5284-4a85-8d6d-7c48d16ec03f)

**Comment by typhonrt** [comment]
It looks like there are general issues with the `dnd5e` group actor award process. If you open the "Rat Loot" group directly from the Foundry sidebar I have not been able to award any of the PC actors with that workflow here locally with latest `dnd5e 4.0.3` . You also generally need to drop actors in the group actor too which your images above show an empty group.

However there is one small improvement in FQL to make. When opening the actor / "Rat Loot", etc. from the quest rewards `editable: false` is passed to the sheet on render. This can be changed from this [line of code / HandlerDetails.js#L734](https://github.com/Forien/foundryvtt-forien-quest-log/blob/master/src/view/preview/HandlerDetails.js#L734)

to: 
```js
const appId = await Utils.showSheetFromUUID(data, { permissionCheck: false, editable: questPreview.canEdit });
```

That will make the sheet editable for those that can edit it and the buttons won't be disabled. However this doesn't fix the apparent bug of no awards being granted from the group sheet itself which might be an active problem in the `dnd5e` game system. 

As mentioned previously `[[/award 1000gp]]` as a custom reward does work when clicked. 

I'm leaving this note here for @Forien to address in a future update.

**Comment by MaineKnight** [comment]
If you access the "Rat Loot" from the right hand side bar and click award this is what you get. Then you simply mark who to award and click the award button.

![From Right Nav](https://github.com/user-attachments/assets/5fbc43f5-072f-4c4b-b9b5-b977de0bf425)
