### ISSUE TITLE
Quest branching

### ISSUE THREAD

**Issue by Forien** [Forien/foundryvtt-forien-quest-log#15]

**Comment by GameMaker** [comment]
Not sure if this is what you mean, but I would also definitely use "sub-quests".
For example, my current quest chain is:
- Campaign goal A
  - Step 1
    - Step 1A
    - Step 1B
    - Step 1C
  - Step 2
etc.
The players can do 1A/B/C in any order, then return to Step 1
Right now, I'm using "Available" for "Campaign Goal", but that's...not really right. Step 1 is still in support of the main storyline quest, but that's not visible in the In Progress tab, so I'm concerned they might lose the connection.
And I'm using Tasks for A/B/C, but then I'm limited to "one level deep", and I don't get rewards for each individual subtask, etc.
I feel like maybe getting rid of Tasks and using sub-quests instead (so it can have its own GM notes, its own treasure, its own privacy settings) would be much more useful.
Or, if not 'getting rid of', at least supporting "quests that depend on other quests".

**Comment by Forien** [comment]
From Discord:

> I imagine I could link quests, so a quest could have parent quest and display on top "part of „XXX” quest", and on parent's side the subquest would display instead of an objective.

So my initial plan is that on Parent Quest, the "linked" quests would appear as objectives, but when clicked, would open new proper Quest Window.

I'm not going to get rid of tasks though, there are instances, where added complexity would be harmful to flow.

**Comment by GameMaker** [comment]
Yeah, that makes sense - sometimes you really just need a Task to be "Do the thing".

So it sounds like your plan is that Objectives can either be Tasks or Sub-Quests (linking to another Quest page). I like it. We'd need some UI design around it so you can tell the difference (like, for example, just underline the text if it's a Quest so it would be obvious that it's a 'link' to somewhere else).
