### ISSUE TITLE
Issue/Feature request: Quest giver actor tweaks

### ISSUE THREAD

**Issue by ExileofBrokenSky** [Forien/foundryvtt-forien-quest-log#2]
**Feature request:** After a quest has been created it would be nice to be able to change the actor associated with it.
**Issue:** The artwork image version of the actor can get squashed if the original artwork has non standard aspect ratio.

example of squish:
![image](https://user-images.githubusercontent.com/28786777/84685216-e633ae80-af07-11ea-9969-b7dd1ecde75b.png)

Normal artwork on char sheet: (Tidy5eSheet)
![image](https://user-images.githubusercontent.com/28786777/84685607-91446800-af08-11ea-8612-7c6c148c3451.png)

**Comment by Forien** [comment]
Resolved in [v0.2.2](https://github.com/Forien/foundryvtt-forien-quest-log/releases/tag/v0.2.2)
