### ISSUE TITLE
[BUG] "Quotes" in quest names and objectives do not load correctly on re-focus

### ISSUE THREAD

**Issue by GameMaker** [Forien/foundryvtt-forien-quest-log#30]
**Describe the bug**
Text in single-line, editable fields (Quest Name, Objective) do not re-load correctly if the text contains a double quote character.

**To Reproduce**
1) Creat a Quest Title or Objective with quotes, for example:
**Go talk to Jimmy "The Greek" Boneswaggler**
2) Blur the field (click elsewhere). Notice it looks correct.
3) Focus the field (click on it) again.
Notice that everything from the first "double quote" on is lost. For example:
**Go talk to Jimmy **
Note that it would even preserve the whitespace at the end. I'm guessing there's some input sanitization going on that's dropping potentially malicious input. Good idea. :)

**Expected behavior**
All text in the field should be there when editing.

**Screenshots**
Before:
![image](https://user-images.githubusercontent.com/1099635/85248667-65dce400-b406-11ea-8f1c-67c9401e5bb3.png)
After clicking on the Quest title field:
![image](https://user-images.githubusercontent.com/1099635/85248686-755c2d00-b406-11ea-9eb9-4e78c36a6316.png)

**Browser:**
Chrome

**Foundry Version:** 
0.6.2

**System:** 
Foundry running on debian 10 buster, nginx as reverse proxy.
Client on Windows 10

**Comment by Forien** [comment]
> System:
> Foundry running on debian 10 buster, nginx as reverse proxy.
> Client on Windows 10

I need to specify it's `Game system:` xD

As discussed on Discord, I will figure out solution for v0.3.3
