### ISSUE TITLE
more flexibility in the 'quest giver' - could be 2-3 actors, a note or an item, in some cases?

### ISSUE THREAD

**Issue by Forien** [Forien/foundryvtt-forien-quest-log#33]

**Comment by sneat** [comment]
Consider that it could be a rumor too (although not sure how that would look).

**Comment by Forien** [comment]
@sneat Basically, right now, Quest Giver is optional, so you could always leave it blank. Blank should work well for rumors.   
I will make changes to allow Items and Journal Entries to be quest givers too. 

I am not yet sure if I want multiple Quest Givers, will see about that.

**Comment by sneat** [comment]
Items and Journals are the more important ones. I really like what you have planned for this module. Good work.

**Comment by Forien** [comment]
Thanks! Might consider to keep an eye out on my Patreon page for notes about update.  
Release post and patch notes are public, other posts posts like sneak peeks and polls are Patron-only.
