### ISSUE TITLE
[BUG] Quest tasks number in the list menu shows hidden tasks – Setting to not count hidden tasks

### ISSUE THREAD

**Issue by JJBocanegra** [Forien/foundryvtt-forien-quest-log#37]
**Describe the bug**
Players can see hidden tasks number on the quests list

**To Reproduce**
1. Create a quest in progress with two tasks, one of them hidden to the players
2. The players can see that the quest have two tasks, even when seeing one when they enter the quest details

**Expected behavior**
Players should only see the number of visible tasks

**Screenshots**
Player View
![image](https://user-images.githubusercontent.com/5797636/85403788-435dde80-b55e-11ea-8010-ce8bfa5c9d73.png)

Quest
![image](https://user-images.githubusercontent.com/5797636/85403828-51abfa80-b55e-11ea-9c7c-4543d213f5a0.png)

**Foundry Version:** v0.6.3

**System:** D&D 5th

**Comment by Forien** [comment]
@JJBocanegra 
This is intended. I'm not saying it's correct, but I wanted it to be that way.

This way players now "there is more to it". 

You can, however, go to module settings and change `Tasks` column to show only number of completed tasks (will count hidden completed tasks though) or hide column completely.

Now I'm thinking if I should add another setting with checkbox "count hidden tasks". We will see.

**Comment by JJBocanegra** [comment]
I see, but I must say that I'll love a setting that allows exactly that, because now I'm just hiding the tasks column because no other option convinces me hehe.

**Comment by Forien** [comment]
Ok then, I will add that setting in nearest update (I am not sure if there will be any intermediate updates between v0.3.3 and v0.4.0 though). Stay tuned!
