### ISSUE TITLE
[BUG] Questlog do not renders in gamemaster screen

### ISSUE THREAD

**Issue by forjadomestre** [Forien/foundryvtt-forien-quest-log#40]
**Module Version:** v0.3.3

First, when I tryed to create a new quest, filled all the boxes, it did not do anything. No quests appeared in the log. Then now, when I click in the quest log ad a GM, it do not opens at all.

Don't know how to reproduce the bug. But I looged as a GM in google chrome and it appeared like this:

![Screenshot_6](https://user-images.githubusercontent.com/67356340/85500041-21de1080-b5b9-11ea-80eb-ffdc97e86902.png)

As a player in the host app, I could open the questlog with no problems. As a GM either in the app or in browser, I coundn't

**Foundry Version: 0.6.3 and 0.6.4 (the bug started in 6.3, I download the 6.4 and the bug persisted)

**Game System: Dungeons & Dragons 5e

**Comment by Forien** [comment]
I have no issues with dnd5e and 0.6.3/0.6.4. 

Error you showed points to something called a `darksheet`, it's probably other module.
On the other hand, I could try to debug the issue, if you are interested, contact me on Discord with link to your game session

**Comment by forjadomestre** [comment]
Yeah, didn't saw tha line. Deleted the "darksheet" module and came across another bug that I figered out how to solve. When the Quest log modula was unistalled, the folders os the quest (those to debug mode) were showing in the Journals. Deleted it manually and reinstaled the quest log module. Now it seens thats all working fine.

**Comment by Forien** [comment]
@forjadomestre deleting the entire `_fql_quests` folder deletes all quest data, it's a very aggresive solution. Anyway, I hope nothing else breaks for you, if it doesn, please open a new Issue. 

Also Disclaimer: Do not link quests in tasks. It's completely unstable. You can link quests in chat and Journals, but not in other Quests. It will be fixed in v0.4.0
