### ISSUE TITLE
Simpler way to link quests into rich text environments

### ISSUE THREAD

**Issue by sneat** [Forien/foundryvtt-forien-quest-log#41]
Thanks for adding the `@Quest[id]` and `@Quest[title]` formats. It would be great if you could add support for dragging a quest into a rich text box as a quick way to add the links.

I've added a (very rough) PR #42 to make it easier to view the appropriate quest id text.

**Comment by Forien** [comment]
The issue with dragging in current build is, that there is no Hook. I would have to manually program every rich text box to add event listener for a `drop` event. 
And while that is possible, it would potentialy create inconsistency with rich text boxes made by other modules. 

I will think of a button to copy link to the quest on click, **I will add it in v0.4.0**


_I believe in Foundry 0.7.0 Hooks for "drop" events will be added so I will have more freedom with deciding how dragging and dropping quests should be handled._

**Comment by Forien** [comment]
Coming in v0.4.0:  

![](https://i.gyazo.com/f26c9452406f69e1b97e72d32d028a35.gif)

**Comment by sneat** [comment]
Nice! That looks really good. Happy for you to close the PR.

**Comment by Forien** [comment]
I like keeping "ehancement" issues open until update, so people won't spam me about the same existing ideas ;)
