### ISSUE TITLE
Overflow of players on the "Manage Quest" tab

### ISSUE THREAD

**Issue by JJBocanegra** [Forien/foundryvtt-forien-quest-log#52]
On the **Manage Quest** tab when editing a quest, if you got a lot of players like me, they doesn't expand to another column, the instead overflow to the **Side Quests** part of the window.

![image](https://user-images.githubusercontent.com/5797636/86121600-8f68d000-bad6-11ea-8482-07c46f3302f0.png)

My suggestions are:
1. Don't give all that space to the bottom row
2. Allow the players to expand to another column
3. Add `overflow-y: scroll` and `max-height: 68%` to `.users` (this is the WORST but is a quick and ugly fix)

They are in order of my personal preference :P.

I want to try to fix it on my own but I don't have much time now, so I'm going to leave this here and if it's not solved by the time I can get some time off, I'll take care of it 😉

**Comment by Forien** [comment]
Fixed partially with v0.4.1 and fully with v0.4.2
