### ISSUE TITLE
Dark Mode issues

### ISSUE THREAD

**Issue by Moerill** [Forien/foundryvtt-forien-quest-log#53]
![image](https://user-images.githubusercontent.com/26152015/86142928-12e4ea00-baf4-11ea-8d58-4ecdfaed4234.png)
The module does mostly work flawlessly with Stryxins DnD5e Dark Mode, but the side tabs of the quest log are not really readable as shown in the screenshot attached.

(though its not default fvtt i'd wish it to be more compatible :sweat_smile: you could listen for the .dark-mode class, which is attached to body)

**Comment by Forien** [comment]
Will think about that :) sounds easier than WFRP4 compatibility issues 😅

**Comment by Moerill** [comment]
All you need is actually just this line of code in your css file:
```
.dark-mode #forien-quest-log nav.log-tabs.bookmarks a.item {
    background: #b5b5b5;
}
```

**Comment by Forien** [comment]
![image](https://user-images.githubusercontent.com/11304207/86239901-70367500-bba0-11ea-83a1-13f86e4b0d77.png)
amount of "Dark" modules scares me :D

Should be now compatible with `D&D5E Dark Mode` by Stryxin.
