### ISSUE TITLE
To many draggable handles[BUG]

### ISSUE THREAD

**Issue by Moerill** [Forien/foundryvtt-forien-quest-log#54]
**Module Version:** v0.4.3

**Describe the bug**
Gotta admit not sure if bug or styling issue.. Decided bug since its propably an issue inside the code.  
![image](https://user-images.githubusercontent.com/26152015/86143940-5724ba00-baf5-11ea-8a20-1be2ddbb95ba.png)  
As can be seen your window has "to many" draggable handles. A window is supposed to have 0 or 1 (i think). Dragging that one onto the canvas results in the entity getting created. 
In the case of the quest log dragging onto the canvas doesn't do a thing. So disabling the handles would propably be the best idea (i think)  
![image](https://user-images.githubusercontent.com/26152015/86144217-abc83500-baf5-11ea-896c-5ee4898956b5.png)
Second screenshot to show what draggable handles are

**Browser:**
 - Firefox

**Foundry Version:** 
- 0.6.4

**Game System:** 
- DnD 5e 0.93

**Comment by Forien** [comment]
Seems to not be from Core. Inspection from Chrome and Fifefox:
![image](https://user-images.githubusercontent.com/11304207/86144604-2db85e00-baf6-11ea-96db-4431d73e4919.png)
![image](https://user-images.githubusercontent.com/11304207/86144648-3a3cb680-baf6-11ea-9e34-f153814e5609.png)

**Comment by Forien** [comment]
If I had to guess, some module adds an element on every "render" hook, without checking if window was already rendered.

**Comment by Moerill** [comment]
ye gotta take it bake
i can't reproduce it anymore.. sry :grimacing:
