### ISSUE TITLE
Unspecific Quest Giver

### ISSUE THREAD

**Issue by sdenec** [Forien/foundryvtt-forien-quest-log#61]
Not all quests come from an NPC and not every NPC needs an Actor assigned. How about a default option with a Placeholder (or selectable) icon and manual name input when creating quests that aren't directly connected to a person?

**Comment by Forien** [comment]
Currently Quest Giver can be:

1. Actor
1. Item
1. Journal Entry
1. blank

I guess you want something like with Abstract Rewards? Custom name and image, not referencing any Entity?

**Comment by sdenec** [comment]
I actually didn't read the drag and drop description carefully enough to see all the option you already offer ... But yeah, a custom name and Image was what I had in mind!
