### ISSUE TITLE
Allow players to edit select details

### ISSUE THREAD

**Issue by mr-bo-jangles** [Forien/foundryvtt-forien-quest-log#62]
I'd like to allow my players to be a bit more self selecting with quests, however if I hand over the ability for them to edit quests then they have full reign to do whatever. 

I'd appreciate there being a middleground where they could accept from and perhaps junk the available (sub)quests on their own.

**Comment by Forien** [comment]
Currently there are two settings:

1. [Module Configuration] "Allow Players to Accept Quests", with this, players can accept any available quests
2. [Manage Quest tab] "Allow players edit Details" with this, players can edit everything on `Details` tab of the quest, they can't add/remove subquests, they can't access `Manage Quest` tab or see `GM Notes`. 

Currently these 2 are only options. More detailed permission management is planned

**Comment by mr-bo-jangles** [comment]
Oh, my bad.
