### ISSUE TITLE
Additional tab for "Bounties"

### ISSUE THREAD

**Issue by CamIsBadAtNames** [Forien/foundryvtt-forien-quest-log#7]
It would be awesome if, in addition to the "On-going, completed, hidden" tabs, we could have a "Bounty/ Job Board" where DMs could post jobs and the players could choose which ones to move to their "on-going" tab.

**Comment by Forien** [comment]
@CamIsBadAtNames Asking for clarification :) 
Would it be safe for me to assume, that this request would be fulfilled by `Available Quests` tab?
Or is it specifically ability of players to "accept" quests that you are requesting?

**Comment by CamIsBadAtNames** [comment]
An Available Quests tab would indeed be perfect for what I'm thinking about! And way more relevant than a bounty board tab haha :)

**Comment by Forien** [comment]
@CamIsBadAtNames okay, then I'm closing this thread, since that's already on my **TODO list**. And I will think about making an optional setting for players to accept quests for themselves as well :) 

Thanks anyway for reaching out! Cheers!
