### ISSUE TITLE
Allow players to control the quest log

### ISSUE THREAD

**Issue by mkahvi** [Forien/foundryvtt-forien-quest-log#75]
Although GM control is nice, players often want to track their own personal quests or just be given the reigns for tracking things on their own, so I'd like for there to be option for players to create and edit quests.

**Comment by Forien** [comment]
That is an option. GM can allow players to edit Quests. This is setting for every Quest, so you can allow players to edit only certain quests:  
![image](https://user-images.githubusercontent.com/11304207/90984798-b7752c80-e577-11ea-8e4b-6011cb5dff3e.png)


There is also option in Module's Settings that allows players to create their own Quests:  
![image](https://user-images.githubusercontent.com/11304207/90984812-d378ce00-e577-11ea-88ff-350cd15b3ab8.png)

**Comment by mkahvi** [comment]
Ah. I'll inform my GM of this. Thanks :)
