### ISSUE TITLE
Button not working

### ISSUE THREAD

**Issue by HippyCraig** [Forien/foundryvtt-forien-quest-log#8]
I just installed the mod, and created an entry or two and clicked the Quest Button at the bottom of the journal page, nothing happens but I found this in the console:

NOTE that only the first click of the button registeres this event any other button presses do not show any errors.

Uncaught (in promise) SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Function.getContent (quest.mjs:115)
    at quest.mjs:132
    at Array.forEach (<anonymous>)
    at Function.getQuests (quest.mjs:131)
    at QuestLog.getData (quest-log.mjs:31)
    at QuestLog._render (foundry.js:3845)
    at QuestLog.render (foundry.js:3819)
    at HTMLButtonElement.<anonymous> (init.js:34)
    at HTMLButtonElement.dispatch (jquery.min.js:2)

**Comment by Forien** [comment]
@HippyCraig you are not supposed to create, edit or open Journal Entries inside the `_fql_` folder. Remove them and create quests from inside Quest Log

**Comment by Linith** [comment]
Should mention this on the front page. I also fell into this trap, I had to delete everything then reload the app for it to work.

**Comment by Forien** [comment]
@Linith sorry, I mentioned it in video, still gonna work on text tutorial. My module isn't the first to use Journals to store data, so I just assumed people are aware of this. 
I think I will hide folder from GM in future updates, just to be safe

**Comment by gogrady4117** [comment]
Dragging and dropping journal entries into the quest description shows a button for the GM but not for the players

**Comment by Forien** [comment]
@gogrady4117 please make new issues about bugs/suggestions/features that are not related to the topic. 
Also, so you don't actually go and do that now, I will answer here:
It's known issue, already resolved in development, **will be live with next update**: 
![image](https://user-images.githubusercontent.com/11304207/84873371-6e8a8e80-b083-11ea-83e3-a9c08bffb231.png)

**Comment by Forien** [comment]
Closing to avoid more Spam.
@HippyCraig if you need more assistance, please reach me on Discord or open another issue.

**Comment by HippyCraig** [comment]
Thanks for the help clearing them worked.
