### ISSUE TITLE
CSS problem

### ISSUE THREAD

**Issue by Linith** [Forien/foundryvtt-forien-quest-log#9]
![cssfix](https://user-images.githubusercontent.com/14077263/84870411-2728e180-b034-11ea-9435-f6e7dea254ff.jpg)

#forien-quest-preview .quest-body .details .tasks-gc .tasks-box .task i.state.fa-check, #forien-quest-preview .quest-body .details .tasks-gc .tasks-box .task i.state.fa-times
Has the following CSS in it. 

    font-size: 1.6em;
    line-height: 1.6em;
    margin-top: -0.4em;
    position: absolute;

I suggest either removing the position or set it to relative. It causing this weird floating css issues.

**Comment by Forien** [comment]
@Linith thanks. I'm not that good with CSS and styling and I haven't tested it with overflowing tasks. I'm sorry for that.

Will fix in upcoming update

**Comment by Forien** [comment]
closed by #24
